name: Prepare Release

on: 
  workflow_dispatch:
    inputs:
      updateType:
        description: The type of update this is.
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:release --if-present
      - run: ls
      - uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
          draft: true
