name: Prepare Release

on: workflow_dispatch

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build:release --if-present
  
  create-archive: 
    name: Create Archive
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/checkout@v2
      
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r dist.zip dist package.json package-lock.json .env.example LICENSE
  
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    needs: create-archive
    steps:
     - uses: actions/checkout@v2
     - name: Draft
     
     
    
        
          
          
